
set(fs_INCLUDES
  include/2d.h
  include/3dfx.h
  include/3d.h
  include/3dinternal.h
  include/ac.h
  include/acm.h
  include/addvariabledlg.h
  include/adjustgriddlg.h
  include/afterburner.h
  include/aibig.h
  include/aigoals.h
  include/ai.h
  include/ailocal.h
  include/alphacolors.h
  include/animplay.h
  include/asteroideditordlg.h
  include/asteroid.h
  include/audiostr.h
  include/awacs.h
  include/barracks.h
  include/beam.h
  include/bgbitmapdlg.h
  include/bmpman.h
  include/briefingeditordlg.h
  include/campaigneditordlg.h
  include/campaignfilelistbox.h
  include/campaigntreeview.h
  include/campaigntreewnd.h
  include/cfilearchive.h
  include/cfile.h
  include/cfilesystem.h
  include/cftp.h
  include/chatbox.h
  include/childfrm.h
  include/chttpget.h
  include/cmdbrief.h
  include/cmdline.h
  include/cmeasure.h
  include/codec1.h
  include/contexthelp.h
  include/controlsconfig.h
  include/convert.h
  include/corkscrew.h
  include/createwingdlg.h
  include/credits.h
  include/crypt.h
  include/cutscenes.h
  include/debriefingeditordlg.h
  include/debris.h
  include/demo.h
  include/dialog1.h
  include/dumpstats.h
  include/editor.h
  include/emp.h
  include/encrypt.h
  include/eventeditor.h
  include/eventmusic.h
  include/exceptionhandler.h
  include/fhash.h
  include/fireballs.h
  include/fishtank.h
  include/fix.h
  include/flak.h
  include/floating.h
  include/font.h
  include/fonttool.h
  include/freddoc.h
  include/fred.h
  include/fredrender.h
  include/fredview.h
  include/freespace.h
  include/freespaceresource.h
  include/fvi.h
  include/gameplayhelp.h
  include/gamesequence.h
  include/gamesnd.h
  include/grid.h
  include/grinternal.h
  include/grgl1.h
  include/gropengl.h
  include/gropenglinternal.h
  include/grwxgl.h
  include/helpeddoc.h
  include/helped.h
  include/helpedline.h
  include/helpedview.h
  include/hudartillery.h
  include/hudbrackets.h
  include/hudconfig.h
  include/hudescort.h
  include/hudets.h
  include/hudgauges.h
  include/hud.h
  include/hudlock.h
  include/hudmessage.h
  include/hudobserver.h
  include/hudresource.h
  include/hudreticle.h
  include/hudshield.h
  include/hudsquadmsg.h
  include/hudtargetbox.h
  include/hudtarget.h
  include/hudwingmanstatus.h
  include/ignoreordersdlg.h
  include/inetgetfile.h
  include/initialships.h
  include/initialstatus.h
  include/joy_ff.h
  include/joy.h
  include/jumpnode.h
  include/keycontrol.h
  include/key.h
  include/levelpaging.h
  include/lighting.h
  include/line.h
  include/linklist.h
  include/localize.h
  include/mainfrm.h
  include/mainhallmenu.h
  include/mainhalltemp.h
  include/management.h
  include/managepilot.h
  include/medals.h
  include/messageeditordlg.h
  include/missionbriefcommon.h
  include/missionbrief.h
  include/missioncampaign.h
  include/missioncmdbrief.h
  include/missiondebrief.h
  include/missiongoalsdlg.h
  include/missiongoals.h
  include/missiongrid.h
  include/missionhotkey.h
  include/missionload.h
  include/missionlog.h
  include/missionloopbrief.h
  include/missionmessage.h
  include/missionnotesdlg.h
  include/missionparse.h
  include/missionpause.h
  include/missionrecommend.h
  include/missionsave.h
  include/missionscreencommon.h
  include/missionshipchoice.h
  include/missionstats.h
  include/missiontraining.h
  include/missionweaponchoice.h
  include/model.h
  include/modelsinc.h
  include/modifyvariabledlg.h
  include/monopub.h
  include/mouse.h
  include/movie.h
  include/multi_campaign.h
  include/multi_data.h
  include/multi_dogfight.h
  include/multi_endgame.h
  include/multi.h
  include/multi_ingame.h
  include/multi_kick.h
  include/multilag.h
  include/multi_log.h
  include/multimsgs.h
  include/multi_obj.h
  include/multi_observer.h
  include/multi_oo.h
  include/multi_options.h
  include/multi_pause.h
  include/multi_pinfo.h
  include/multi_ping.h
  include/multi_pmsg.h
  include/multi_rate.h
  include/multi_respawn.h
  include/multi_team.h
  include/multiteamselect.h
  include/multiui.h
  include/multi_update.h
  include/multiutil.h
  include/multi_voice.h
  include/multi_xfer.h
  include/muzzleflash.h
  include/mvelib.h
  include/neb.h
  include/neblightning.h
  include/nebula.h
  include/oal_capture.h
  include/oal_efx.h
  include/oal.h
  include/objcollide.h
  include/object.h
  include/objectsnd.h
  include/observer.h
  include/operatorargtypeselect.h
  include/optionsmenu.h
  include/optionsmenumulti.h
  include/orienteditor.h
  include/osapi.h
  include/osregistry.h
  include/outwnd.h
  include/packunpack.h
  include/palman.h
  include/parselo.h
  include/particle.h
  include/pcxutils.h
  include/physics.h
  include/player.h
  include/playermenu.h
  include/playerstarteditor.h
  include/pofview.h
  include/popupdead.h
  include/popup.h
  include/prefsdlg.h
  include/psnet2.h
  include/psnet.h
  include/pstypes.h
  include/radar.h
  include/readyroom.h
  include/rect.h
  include/redalert.h
  include/reinforcementeditordlg.h
  include/resource.h
  include/rtvoice.h
  include/scoring.h
  include/scramble.h
  include/sexp.h
  include/sexp_tree.h
  include/shieldsysdlg.h
  include/shipchecklistbox.h
  include/shipclasseditordlg.h
  include/shipcontrails.h
  include/shipeditordlg.h
  include/shipflagsdlg.h
  include/shipfx.h
  include/shipgoalsdlg.h
  include/ship.h
  include/shiphit.h
  include/ship_select.h
  include/shipspecialdamage.h
  include/shockwave.h
  include/snazzyui.h
  include/sound.h
  include/spline.h
  include/stand_gui.h
  include/starfieldeditor.h
  include/starfield.h
  include/staticrand.h
  include/stats.h
  include/stdafx.h
  include/subsysdamage.h
  include/supernova.h
  include/swarm.h
  include/systemvars.h
  include/techmenu.h
  include/textviewdlg.h
  include/tga.h
  include/tgautils.h
  include/timer.h
  include/tmapper.h
  include/trails.h
  include/trainingmenu.h
  include/uidefs.h
  include/ui.h
  include/unix.h
  include/vecmat.h
  include/version.h
  include/waypointpathdlg.h
  include/weaponeditordlg.h
  include/weapon.h
  include/wing_editor.h
  include/wing.h
)

