include_directories(
  ${PROJECT_SOURCE_DIR}/include
  ${SDL2_INCLUDE_DIRS}
  ${OPENAL_INCLUDE_DIR}
)

set(code_SOURCE
  anim/animplay.cpp
  anim/packunpack.cpp
  asteroid/asteroid.cpp
  bmpman/bmpman.cpp
  cfile/cfile.cpp
  cfile/cfilearchive.cpp
  cfile/cfilelist.cpp
  cfile/cfilesystem.cpp
  cmdline/cmdline.cpp
  cmeasure/cmeasure.cpp
  controlconfig/controlsconfig.cpp
  controlconfig/controlsconfigcommon.cpp
  cutscene/cutscenes.cpp
  debris/debris.cpp
  debugconsole/console.cpp
  demo/demo.cpp
  fireball/fireballs.cpp
  fireball/warpineffect.cpp
  gamehelp/contexthelp.cpp
  gamehelp/gameplayhelp.cpp
  gamesequence/gamesequence.cpp
  gamesnd/eventmusic.cpp
  gamesnd/gamesnd.cpp
  globalincs/alphacolors.cpp
  globalincs/crypt.cpp
  globalincs/systemvars.cpp
  globalincs/version.cpp
  graphics/2d.cpp
  graphics/font.cpp
  graphics/gropengl1.cpp
  graphics/gropengl1render.cpp
  graphics/gropengl1texture.cpp
  graphics/gropengl.cpp
  hud/hud.cpp
  hud/hudartillery.cpp
  hud/hudbrackets.cpp
  hud/hudconfig.cpp
  hud/hudescort.cpp
  hud/hudets.cpp
  hud/hudlock.cpp
  hud/hudmessage.cpp
  hud/hudobserver.cpp
  hud/hudreticle.cpp
  hud/hudshield.cpp
  hud/hudsquadmsg.cpp
  hud/hudtarget.cpp
  hud/hudtargetbox.cpp
  hud/hudwingmanstatus.cpp
  inetfile/cftp.cpp
  inetfile/chttpget.cpp
  inetfile/inetgetfile.cpp
  io/joy.cpp
  io/joy_ff.cpp
  io/key.cpp
  io/keycontrol.cpp
  io/mouse.cpp
  io/timer.cpp
  jumpnode/jumpnode.cpp
  lighting/lighting.cpp
  localization/fhash.cpp
  localization/localize.cpp
  localization/strings_tbl_fs1.cpp
  math/fix.cpp
  math/floating.cpp
  math/fvi.cpp
  math/spline.cpp
  math/staticrand.cpp
  math/vecmat.cpp
  menuui/barracks.cpp
  menuui/credits.cpp
  menuui/fishtank.cpp
  menuui/mainhallmenu.cpp
  menuui/mainhalltemp.cpp
  menuui/optionsmenu.cpp
  menuui/optionsmenumulti.cpp
  menuui/playermenu.cpp
  menuui/readyroom.cpp
  menuui/snazzyui.cpp
  menuui/techmenu.cpp
  menuui/trainingmenu.cpp
  mission/missionbriefcommon.cpp
  mission/missioncampaign.cpp
  mission/missiongoals.cpp
  mission/missiongrid.cpp
  mission/missionhotkey.cpp
  mission/missionload.cpp
  mission/missionlog.cpp
  mission/missionmessage.cpp
  mission/missionparse.cpp
  mission/missiontraining.cpp
  missionui/chatbox.cpp
  missionui/missionbrief.cpp
  missionui/missioncmdbrief.cpp
  missionui/missiondebrief.cpp
  missionui/missionloopbrief.cpp
  missionui/missionpause.cpp
  missionui/missionrecommend.cpp
  missionui/missionscreencommon.cpp
  missionui/missionshipchoice.cpp
  missionui/missionstats.cpp
  missionui/missionweaponchoice.cpp
  missionui/redalert.cpp
  model/modelcollide.cpp
  model/modelinterp.cpp
  model/modeloctant.cpp
  model/modelread.cpp
  movie/decoder16.cpp
  movie/movie.cpp
  movie/mve_audio.cpp
  movie/mvelib.cpp
  movie/mveplayer.cpp
  nebula/neb.cpp
  nebula/neblightning.cpp
  network/multi.cpp
  network/multi_campaign.cpp
  network/multi_data.cpp
  network/multi_dogfight.cpp
  network/multi_endgame.cpp
  network/multi_ingame.cpp
  network/multi_kick.cpp
  network/multi_log.cpp
  network/multi_obj.cpp
  network/multi_observer.cpp
  network/multi_oo.cpp
  network/multi_options.cpp
  network/multi_pause.cpp
  network/multi_pinfo.cpp
  network/multi_ping.cpp
  network/multi_pmsg.cpp
  network/multi_rate.cpp
  network/multi_respawn.cpp
  network/multi_team.cpp
  network/multi_update.cpp
  network/multi_voice.cpp
  network/multi_xfer.cpp
  network/multilag.cpp
  network/multimsgs.cpp
  network/multiteamselect.cpp
  network/multiui.cpp
  network/multiutil.cpp
  network/psnet.cpp
  network/psnet2.cpp
  object/collidedebrisship.cpp
  object/collidedebrisweapon.cpp
  object/collideshipship.cpp
  object/collideshipweapon.cpp
  object/collideweaponweapon.cpp
  object/objcollide.cpp
  object/object.cpp
  object/objectsnd.cpp
  object/objectsort.cpp
  observer/observer.cpp
  osapi/osapi.cpp
  osapi/osregistry.cpp
  osapi/outwnd.cpp
  palman/palman.cpp
  parse/encrypt.cpp
  parse/parselo.cpp
  parse/sexp.cpp
  particle/particle.cpp
  pcxutils/pcxutils.cpp
  physics/physics.cpp
  playerman/managepilot.cpp
  playerman/playercontrol.cpp
  popup/popup.cpp
  popup/popupdead.cpp
  radar/radar.cpp
  render/3dclipper.cpp
  render/3ddraw.cpp
  render/3dlaser.cpp
  render/3dmath.cpp
  render/3dsetup.cpp
  ship/afterburner.cpp
  ship/ai.cpp
  ship/aibig.cpp
  ship/aicode.cpp
  ship/aigoals.cpp
  ship/awacs.cpp
  ship/shield.cpp
  ship/ship.cpp
  ship/shipcontrails.cpp
  ship/shipfx.cpp
  ship/shiphit.cpp
  sound/acm.cpp
  sound/audiostr.cpp
  sound/oal.cpp
  sound/oal_capture.cpp
  sound/oal_efx.cpp
  sound/rtvoice.cpp
  sound/sound.cpp
  starfield/nebula.cpp
  starfield/starfield.cpp
  starfield/supernova.cpp
  stats/medals.cpp
  stats/scoring.cpp
  stats/stats.cpp
  tgautils/tgautils.cpp
  ui/button.cpp
  ui/checkbox.cpp
  ui/gadget.cpp
  ui/icon.cpp
  ui/inputbox.cpp
  ui/keytrap.cpp
  ui/listbox.cpp
  ui/radio.cpp
  ui/scroll.cpp
  ui/slider.cpp
  ui/slider2.cpp
  ui/uidraw.cpp
  ui/uimouse.cpp
  ui/window.cpp
  vcodec/codec1.cpp
  weapon/beam.cpp
  weapon/corkscrew.cpp
  weapon/emp.cpp
  weapon/flak.cpp
  weapon/muzzleflash.cpp
  weapon/shockwave.cpp
  weapon/swarm.cpp
  weapon/trails.cpp
  weapon/weapons.cpp
)

if(WIN32)
  set(code_SOURCE
    ${code_SOURCE}
    network/stand_gui.cpp
  )
else()
  set(code_SOURCE
    ${code_SOURCE}
    network/stand_gui-unix.cpp
    platform/unix.cpp
  )
endif()

add_library(code STATIC ${code_SOURCE})
